# Generated by Django 4.2.4 on 2023-08-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message_bot_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='message',
        ),
    ]
